//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proveduria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPRTA_ARTICULO_BODEGA
    {
        public byte ID_BODEGA { get; set; }
        public int ID_ITEM { get; set; }
        public Nullable<int> CANTIDAD_MAXIMA { get; set; }
        public Nullable<decimal> CANTIDAD_ACTUAL { get; set; }
        public Nullable<decimal> CANTIDAD_INICIO { get; set; }
        public Nullable<int> CANTIDAD_CRITICA { get; set; }
        public Nullable<int> CANTIDAD_MINIMA { get; set; }
        public Nullable<decimal> CANTIDAD_BAJA { get; set; }
        public Nullable<int> CANTIDAD_OC { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public string ESTADO { get; set; }
        public string UBICACION { get; set; }
    
        public virtual EPRTA_ITEM EPRTA_ITEM { get; set; }
        public virtual EPRTA_BODEGA EPRTA_BODEGA { get; set; }
    }
}
