//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_ITEMS
    {
        public string ITE_CODIGO { get; set; }
        public string ITE_DES { get; set; }
        public string ITE_UNIDAD { get; set; }
        public Nullable<System.DateTime> ITE_FECULING { get; set; }
        public Nullable<System.DateTime> ITE_FECULEGR { get; set; }
        public Nullable<System.DateTime> ITE_FECEXP { get; set; }
        public Nullable<decimal> ITE_VALANT { get; set; }
        public Nullable<decimal> ITE_VALACT { get; set; }
        public string ITE_ESTADO { get; set; }
        public string ITE_OBSERV { get; set; }
        public Nullable<int> ITE_CNTUNI { get; set; }
        public string GRU_CODIGO { get; set; }
        public string ITE_MARCA { get; set; }
        public string ITE_MODELO { get; set; }
        public string TIPO { get; set; }
    
        public virtual INV_GRUPO INV_GRUPO { get; set; }
        public virtual INV_MEDIDA INV_MEDIDA { get; set; }
    }
}
