//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_GRUPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_GRUPO()
        {
            this.INV_ITEMS = new HashSet<INV_ITEMS>();
        }
    
        public string GRU_CODIGO { get; set; }
        public string GRU_DESCRIP { get; set; }
        public string GRU_ESTADO { get; set; }
        public string CTA_CONTABLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_ITEMS> INV_ITEMS { get; set; }
    }
}
