//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_BODEGA
    {
        public decimal ID_CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string DESC_ABREVIADA { get; set; }
        public string ESTADO { get; set; }
        public string RESPONSABLE { get; set; }
        public string TIPO { get; set; }
    }
}
