//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OracleEntities : DbContext
    {
        public OracleEntities()
            : base("name=OracleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INV_BODEGA> INV_BODEGA { get; set; }
        public virtual DbSet<INV_GRUPO> INV_GRUPO { get; set; }
        public virtual DbSet<INV_ITEMS> INV_ITEMS { get; set; }
        public virtual DbSet<INV_MEDIDA> INV_MEDIDA { get; set; }
    }
}
