//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proveduria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASPNETUSERS
    {
        public string ID { get; set; }
        public string EMAIL { get; set; }
        public decimal EMAILCONFIRMED { get; set; }
        public string PASSWORDHASH { get; set; }
        public string SECURITYSTAMP { get; set; }
        public string PHONENUMBER { get; set; }
        public decimal PHONENUMBERCONFIRMED { get; set; }
        public decimal TWOFACTORENABLED { get; set; }
        public Nullable<System.DateTime> LOCKOUTENDDATEUTC { get; set; }
        public decimal LOCKOUTENABLED { get; set; }
        public decimal ACCESSFAILEDCOUNT { get; set; }
        public string USERNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
    }
}
