//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proveduria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPRTA_SECUENCIA
    {
        public short ID_SECUENCIA { get; set; }
        public byte ID_TIPO_MOVIMIENTO { get; set; }
        public Nullable<short> ANIO { get; set; }
        public Nullable<int> SECUENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_CREA { get; set; }
        public Nullable<System.DateTime> FECHA_ULTIMA_SECUENCIA { get; set; }
    
        public virtual EPRTA_TIPO_MOVIMIENTO EPRTA_TIPO_MOVIMIENTO { get; set; }
    }
}
