//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proveduria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPRTA_CORTE_INVENTARIO_DET
    {
        public long ID_CORTE_DETALLE { get; set; }
        public Nullable<int> ID_CORTE { get; set; }
        public Nullable<int> ID_ITEM { get; set; }
        public Nullable<decimal> COSTO_PROMEDIO { get; set; }
        public Nullable<decimal> CANTIDAD_MAXIMA { get; set; }
        public Nullable<decimal> CANTIDAD_ACTUAL { get; set; }
        public Nullable<decimal> CANTIDAD_INICIO { get; set; }
        public Nullable<decimal> CANTIDAD_CRITICA { get; set; }
        public Nullable<decimal> CANTIDAD_MINIMA { get; set; }
        public Nullable<decimal> CANTIDAD_BAJA { get; set; }
        public Nullable<decimal> CANTIDAD_OC { get; set; }
        public Nullable<decimal> TOTAL_STOCK { get; set; }
    
        public virtual EPRTA_CORTE_INVENTARIO EPRTA_CORTE_INVENTARIO { get; set; }
        public virtual EPRTA_ITEM EPRTA_ITEM { get; set; }
    }
}
