//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proveduria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPRTA_BODEGA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EPRTA_BODEGA()
        {
            this.EPRTA_ARTICULO_BODEGA = new HashSet<EPRTA_ARTICULO_BODEGA>();
            this.EPRTA_MOVIMIENTO = new HashSet<EPRTA_MOVIMIENTO>();
            this.EPRTA_CORTE_INVENTARIO = new HashSet<EPRTA_CORTE_INVENTARIO>();
        }
    
        public byte ID_BODEGA { get; set; }
        public string NOMBRE { get; set; }
        public string ESTADO { get; set; }
        public string CUENTA_CONTABLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPRTA_ARTICULO_BODEGA> EPRTA_ARTICULO_BODEGA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPRTA_MOVIMIENTO> EPRTA_MOVIMIENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPRTA_CORTE_INVENTARIO> EPRTA_CORTE_INVENTARIO { get; set; }
    }
}
