//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proveduria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPRTA_CORTE_INVENTARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EPRTA_CORTE_INVENTARIO()
        {
            this.EPRTA_CORTE_INVENTARIO_DET = new HashSet<EPRTA_CORTE_INVENTARIO_DET>();
        }
    
        public int ID_CORTE { get; set; }
        public Nullable<byte> ID_BODEGA { get; set; }
        public Nullable<System.DateTime> FECHA_CORTE { get; set; }
        public string USUARIO_CORTE { get; set; }
        public Nullable<int> NUMERO_ITEMS { get; set; }
        public Nullable<decimal> TOTAL_CORTE { get; set; }
    
        public virtual EPRTA_BODEGA EPRTA_BODEGA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPRTA_CORTE_INVENTARIO_DET> EPRTA_CORTE_INVENTARIO_DET { get; set; }
    }
}
