//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proveduria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DEPARTAMENTO
    {
        public short DIRECCION { get; set; }
        public byte CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO { get; set; }
        public string SIGLA { get; set; }
        public Nullable<int> CARGO { get; set; }
    }
}
