//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proveduria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EMPLEADO
    {
        public int CODIGO { get; set; }
        public string CEDULA { get; set; }
        public string EMPLEADO { get; set; }
        public Nullable<int> GRADO_ID { get; set; }
        public string GRADO { get; set; }
        public Nullable<int> CARGO_ID { get; set; }
        public string CARGO { get; set; }
        public Nullable<short> DIRECCION_ID { get; set; }
        public string USUARIO { get; set; }
        public string ESTADO { get; set; }
        public Nullable<byte> DEPARTAMENTO_ID { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string USUARIO_JEFE_DEPARTAMENTO { get; set; }
        public string DIRECCION { get; set; }
    }
}
