//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proveduria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ORDEN_COMPRA_DETALLE
    {
        public decimal SECUENCIA_LINEA { get; set; }
        public decimal ANIO { get; set; }
        public int NUMERO_ORDEN { get; set; }
        public string CODIGO { get; set; }
        public int ID_ITEM { get; set; }
        public Nullable<int> CANTIDAD_PEDIDA { get; set; }
        public string ESTADO { get; set; }
    
        public virtual VW_ORDEN_COMPRA VW_ORDEN_COMPRA { get; set; }
        public virtual EPRTA_ITEM EPRTA_ITEM { get; set; }
    }
}
