//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proveduria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ORDEN_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VW_ORDEN_COMPRA()
        {
            this.VW_ORDEN_COMPRA_DETALLE = new HashSet<VW_ORDEN_COMPRA_DETALLE>();
            this.EPRTA_MOVIMIENTO = new HashSet<EPRTA_MOVIMIENTO>();
        }
    
        public short ANIO { get; set; }
        public int NUMERO_ORDEN { get; set; }
        public string PROVEEDOR { get; set; }
        public Nullable<System.DateTime> FECHA_AUTORIZACION { get; set; }
        public string FACTURA { get; set; }
        public Nullable<System.DateTime> FECHA_EMISION { get; set; }
        public string TIPO { get; set; }
        public string ESTADO { get; set; }
        public string DEPARTAMENTO_SOLICITA { get; set; }
        public string EMPLEADO_SOLICITA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VW_ORDEN_COMPRA_DETALLE> VW_ORDEN_COMPRA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPRTA_MOVIMIENTO> EPRTA_MOVIMIENTO { get; set; }
    }
}
